### ISSUE TITLE
As a user, I want to add a new task to my to-do list

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#1]
# Task
- [ ] Create an input field or dialog to capture the task name and add it to the list.

# Requirements
- [ ] Create a TextField to capture the task name.
- [ ] Add a Button that triggers the addition of the task.
- [ ] Store the task in memory or a local list.
- [ ] Update the UI dynamically to show the added task.
- [ ] Optionally, clear the input field after adding the task.
