### ISSUE TITLE
As a user, I want the app to support dark mode

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#13]
# Task
- [ ] Add theme toggling using DayNight themes in Android.

# Requirements
- [ ] Implement DayNight theme support in Android.
- [ ] Allow the user to toggle between light and dark modes in settings.
- [ ] Automatically switch themes based on the system settings or user preference.
