### ISSUE TITLE
As a user, I want to prioritize tasks by assigning them high, medium, or low priority

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#14]
# Task
- [ ] Add priority levels with sorting options

# Requirements
- [ ] Add a dropdown or radio buttons to allow the user to assign a priority to each task.
- [ ] Store the priority level for each task.
- [ ] Sort tasks by priority (e.g., high priority at the top).
- [ ] Optionally, visually distinguish tasks based on their priority level (e.g., color code).
