### ISSUE TITLE
As a user, I want to view all my tasks in a list

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#2]
# Task
- [ ] Implement a 'RecyclerView' to display tasks dynamically.

# Requirements
- [ ] Use LazyColumn to show a list of tasks.
- [ ] Each item should display the task name.
- [ ] Ensure the tasks are added dynamically to the list and are displayed as they are added.
