### ISSUE TITLE
As a user, I want to mark tasks as completed

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#3]
# Task
- [ ] Add a checkbox next to each task to toggle its "completed" state.

# Requirements
- [ ] Add a Checkbox next to each task.
- [ ] When checked, the task is marked as completed.
- [ ] Completed tasks can be visually distinguished (e.g., strike-through text).
- [ ] Store the state (completed or not) of each task.
