### ISSUE TITLE
As a user, I want to delete tasks that I no longer need

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#4]
# Task 
- [ ] Add a delete button or swipe gesture to remove tasks.

# Requirements
- [ ] Implement a delete button next to each task or swipe-to-delete gesture.
- [ ] Tasks should be removed from the list upon deletion.
- [ ] Update the list dynamically after the task is removed.
