### ISSUE TITLE
As a user, I want my tasks to be saved, so I don't lose them when I close the app

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#5]
# Task
- [ ] Use 'Room' or SharedPreferences for data persistence.

# Requirements
- [ ] Implement Room Database to store tasks persistently.
- [ ] Save tasks to the database when added and retrieved when the app starts.
- [ ] Alternatively, use SharedPreferences for simple data persistence if the app doesn’t need complex querying.
