### ISSUE TITLE
As a user, I want to see completed tasks at the bottom of the list

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#6]
# Task
- [ ] Sort the tasks by their completion status.

# Requirements
- [ ] Use a sorting algorithm to display incomplete tasks at the top.
- [ ] Completed tasks should appear at the bottom.
- [ ] Implement sorting either by using the UI or sorting data at the backend.
