### ISSUE TITLE
As a user, I want to edit the name of a task if I made a mistake

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#7]
# Task
- [ ] Implement a dialog or in-place editing for task names.

# Requirements
- [ ] Add an "Edit" button next to each task.
- [ ] When clicked, allow the user to modify the task name either in-place or in a dialog.
- [ ] Save the edited task back to the database or local storage.
- [ ] Reflect the changes immediately in the UI.
