### ISSUE TITLE
As a user, I want to set a deadline for each task and be notified when it’s due

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#8]
# Task
- [ ] Add a date picker for deadlines and set notifications with AlarmManager or WorkManager.

# Requirements
- [ ] Add a DatePickerDialog to allow the user to set a deadline for each task.
- [ ] Store the selected deadline in the task.
- [ ] Set a notification using AlarmManager or WorkManager to remind the user when the deadline is near.
- [ ] Implement custom notification styling.
