### ISSUE TITLE
As a user, I want to categorize tasks (e.g., work, personal, shopping)

### ISSUE THREAD

**Issue by idilyilmz** [idilyilmz/todolist#9]
# Task
- [ ] Add a dropdown menu or tags to catagorize tasks

# Requirements
- [ ] Add a dropdown (Spinner) or a tag system to each task.
- [ ] Allow the user to choose from a predefined set of categories (e.g., "Work", "Personal", "Shopping").
- [ ] Display the task category next to the task name.
- [ ] Optionally, allow filtering tasks by category.
